### ISSUE TITLE
Load Balancing max. Smart Meter Current wrong in HA?

### ISSUE THREAD

**Issue by ltv8** [leeyuentuen/alfen_wallbox#101]
Hello,

First of all: many thanks for making this fantastic integration! I really like it and I think it is super useful.

However, I think I encountered a little bug / glitch. 
I can not set the max. Smart Meter Current higher then 16A. (as i have a 1x35A grid connection, I would like to be able to set the load balancing limit to 34A. 

So I have set it to 34A in the ACE Installer, but when I touch the slider in the integration in HA it is not possible to put it higher than 16A.
Would it be possible to increase this value to at least 35A? 

Many thanks for your response!

**Comment by ltv8** [comment]
Hello, 

Anybody else also experiencing this issue? Would it be possible to have a quick look at it? 
Many thanks in advance!

**Comment by leeyuentuen** [comment]
what value did you see in ace installer? i suppose the max is normally 32A?

**Comment by ltv8** [comment]
I have tried to set it to, by example, 100A and this is possible (in ACE). 

I have set it to the desired 34A and this works also, but not in HA.

**Comment by leeyuentuen** [comment]
not sure, but i think i have this changed in the beta version here from 32A to 40A:
https://github.com/leeyuentuen/alfen_wallbox/releases/tag/2.7.24

**Comment by ltv8** [comment]
Hello, it does not have to do with any license. I think there is some misunderstanding:)

It is about the smart meter max.current when load balancing. 

For example: I have 1x35A main fuse in my home. 
I charge at 1x32A = 7.4kW. 
I want to set the load balancing max current limit to 34A so my main fuse does not blow when I switch on for example the oven. 

When my oven uses 10A, the charging station knows it is able to use 34A - 10A = 24A. 

However, I can not set the load balancing max. current to higher than 16A in Home Assistant, but I can set it to for example 100A in ACE INSTALLER. 

This should in my view also be higher in Home Assistant :)

**Comment by leeyuentuen** [comment]
@ltv8 here is a beta change: https://github.com/leeyuentuen/alfen_wallbox/releases/tag/2.7.30
can you check if you mean for this?

**Comment by ltv8** [comment]
Hello, how can I use beta? Highest version I can update to is 2.7.29.

Kind regards

________________________________

**Comment by leeyuentuen** [comment]
hacs -> search for alfen wallbox -> ... (on the right top) -> redownload --> check the show beta version
![image](https://github.com/leeyuentuen/alfen_wallbox/assets/1487966/06d60ffc-0996-4009-bb1b-14381144b215)

**Comment by leeyuentuen** [comment]
great to hear it works, but i still need to check if this value in the ace installer if it is the correct way

**Comment by TeddyTBP** [comment]
Hi 

Not sure if related to this change but following values say max 16A in the slider and don't seem to update anymore. 

number.wally_max_station_current
number.wally_power_connector_max_current_socket_1


<img width="458" alt="image" src="https://github.com/leeyuentuen/alfen_wallbox/assets/134924704/55ff32a6-2aec-46b8-a9b0-29eaf58d8312">

**Comment by leeyuentuen** [comment]
> Hi
> 
> Not sure if related to this change but following values say max 16A in the slider and don't seem to update anymore.
> 
> number.wally_max_station_current number.wally_power_connector_max_current_socket_1
> 
> <img alt="image" width="458" src="https://private-user-images.githubusercontent.com/134924704/324272236-55ff32a6-2aec-46b8-a9b0-29eaf58d8312.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3MjcxMTQsIm5iZiI6MTcxMzcyNjgxNCwicGF0aCI6Ii8xMzQ5MjQ3MDQvMzI0MjcyMjM2LTU1ZmYzMmE2LTJhZWMtNDZiOC1hOWIwLTI5ZWFmNThkODMxMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMVQxOTEzMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MGM3MWYxOTM2YTliMGE5YzM1MzY4Njk3Y2U5N2MzZGRjN2Y3MDY5Mjg2M2E4YmJhODZjYjNiMGQ5YzViNTY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0xRhDUQTbduTHX-J2-l6R7npwh0Hj2Y6qttPwOysON0">

it has long time ago changed, 
https://github.com/leeyuentuen/alfen_wallbox/commit/4cad244ccc1a118b29113cfd76af214f09f68a23#diff-d5887da63095432e6c3b94aa2308f4eb941be37d35e5cd13eff050c0a17abb2fR463-R472

if related if there is a 32A license? do you have a 32A license? or did i implement here wrong

**Comment by TeddyTBP** [comment]
I have all licenses except e-giro. 

But i see since i switcht to beta releases that all license are off in the sensor data. Should i revert to non beta it sees my licenses and code works ass excepted. Even just tested .37 and then license are all off

**Comment by leeyuentuen** [comment]
@TeddyTBP  can you check the new beta version, I've put a warning in the log, but I don't have the 32A license
can you just paste the result that should be like this:
`['LoadBalancing_Active', 'RFIDReader', 'PersonalizedDisplay', 'Mobile3G4G', 'ObjectID']`

https://github.com/leeyuentuen/alfen_wallbox/releases/tag/2.7.38
I need to know if the value for 32A is "HighPowerSockets"
