### ISSUE TITLE
no connection HA

### ISSUE THREAD

**Issue by alphabravocharly72** [leeyuentuen/alfen_wallbox#106]
Hello, since a few weeks the WB has no connection to HA. I didnt change anythings.
Can someone hlep me?
Thx
aloha

**Comment by leeyuentuen** [comment]
maybe restart the ha and see in the log what you see about the wallbox? and paste the log here maybe we should know more.

**Comment by alphabravocharly72** [comment]
It stucks at the initialize. See screenshoot.
![alfen screenshoot](https://github.com/leeyuentuen/alfen_wallbox/assets/59312982/eb08a3f8-359a-4325-8da3-7f1adf5f1250)

**Comment by leeyuentuen** [comment]
i think username is admin

**Comment by alphabravocharly72** [comment]
Yes, this was the issue.
Thx fpr helping
