### ISSUE TITLE
Auto reboot on the latest release 2.7.28

### ISSUE THREAD

**Issue by leeyuentuen** [leeyuentuen/alfen_wallbox#107]
@ikruglov. I'm not sure if it is related, but after the change of the timeout. it seems I got here back after the 8-hour reboot 
issue from here: https://github.com/leeyuentuen/alfen_wallbox/issues/30

I'm going back to old version and see if this is the issue
![image](https://github.com/leeyuentuen/alfen_wallbox/assets/1487966/11c868fd-9256-4edd-8c84-6dccd17b72ed)

**Comment by ikruglov** [comment]
Interesting. It seems that I have the same pattern yeah, let's revert and find a better solution

**Comment by ikruglov** [comment]
I'll try to keep the interval at 30s, but increase the timeout back to 90s. Let's see how it goes.

**Comment by leeyuentuen** [comment]
i'm on 2.7.25.1 version, and it doesn't have the issue. so it should be something on next few version changes.

let me know if it's solved with that change

**Comment by WimBra** [comment]
I have the same issue...
reboots every 9h30m

I'm  gonna roll back to 2.7.25.1

**Comment by ikruglov** [comment]
It seems that the culprit is the increase of interval to 30s. I highly suspect that the reason for this is the following:

When the interval is 5s the code rarely hits `_login()` function (actually, it hits only once, at the begging). Because 5s interval is fast enough to keep Alfen's internal session live.

However, when the interval is 30s, the logout timeout hits on Alfen's side. At least this is what I see in the logs. Every update triggers "GET with login" message. As a result, we generate a login request every 30s which, I think, somehow overloads internal Alfen's state and causes a reboot after ~8-9h.

**Comment by ikruglov** [comment]
@leeyuentuen please revert https://github.com/ikruglov/alfen_wallbox/commit/0085558e70286079beeb6c467c716837de2e04ac for now. I'll see if there is a better solution.

**Comment by leeyuentuen** [comment]
i've just roll back
https://github.com/leeyuentuen/alfen_wallbox/releases/tag/2.7.29

**Comment by barthoefs** [comment]
Same issue here:
![image](https://github.com/leeyuentuen/alfen_wallbox/assets/89918293/8601fb01-d8bb-4a28-bb66-5f0fc3dd5c28)
What is the solution?

**Comment by leeyuentuen** [comment]
> @leeyuentuen I have the same issue here: ![image](https://private-user-images.githubusercontent.com/89918293/322732297-8601fb01-d8bb-4a28-bb66-5f0fc3dd5c28.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyNTExNzIsIm5iZiI6MTcxMzI1MDg3MiwicGF0aCI6Ii84OTkxODI5My8zMjI3MzIyOTctODYwMWZiMDEtZDhiYi00YTI4LWJiNjYtNWYwZmMzZGQ1YzI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDA3MDExMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyNTRmNzlmMjUxM2FkM2Q4NjhlNjUxNTQ4Y2U4N2Y2YWM5OTU1NjZkNmU4NDBmMWQ3N2EzOTQ3MzYzMTZiOTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VAO0ZXuFLxCxk8RzshzvKJrqV2BQ372Tqv5Fik7qjsQ) What is the solution?

which version are you using?

**Comment by barthoefs** [comment]
> > @leeyuentuen I have the same issue here: ![image](https://private-user-images.githubusercontent.com/89918293/322732297-8601fb01-d8bb-4a28-bb66-5f0fc3dd5c28.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyNTExNzIsIm5iZiI6MTcxMzI1MDg3MiwicGF0aCI6Ii84OTkxODI5My8zMjI3MzIyOTctODYwMWZiMDEtZDhiYi00YTI4LWJiNjYtNWYwZmMzZGQ1YzI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDA3MDExMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyNTRmNzlmMjUxM2FkM2Q4NjhlNjUxNTQ4Y2U4N2Y2YWM5OTU1NjZkNmU4NDBmMWQ3N2EzOTQ3MzYzMTZiOTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VAO0ZXuFLxCxk8RzshzvKJrqV2BQ372Tqv5Fik7qjsQ) What is the solution?
> 
> which version are you using?

I have seen it now. HA didnt show the newer version, only after reloading the info. Updated to 2.7.29, will monitor...
Thanks!

**Comment by ikruglov** [comment]
@leeyuentuen, I got to the bottom of this problem. It's simple. It's not on Alfen's side (well, completely at least), it's on `alfen_wallbox` side as well.

But before I move forward, we need to be clear about one thing: Alfen requires you to use the same TCP connection for sending GET/POST which you used for `api/login` call.

1. As I mentioned before, there is an Alfen bug or something that makes it reboot every N hours if you do constant `api/login` requests. Alfen perhaps leaks file descriptors or something.
2. However, there is also a problem on `alfen_wallbox` side. In particular, the `self.session` object which does connection pooling which is mandatory has `keepalive_timeout` set to 15s. This is a default value.
3. So, when `SCAN_INTERVAL` is any value below 15s (which is true for `SCAN_INTERVAL=5`), `self.session` successfully reuses connections.
4. However, when `SCAN_INTERVAL` is, for instance, 30s. `self.session` internally closes TCP connections. As the result, this force it to establish a new connection and hence do a new `api/login` on every sensor update round.

The solution is simple. We just need to increase `keepalive_interval` to a higher value. I'll prepare a PR for that.

**Comment by leeyuentuen** [comment]
> @leeyuentuen, I got to the bottom of this problem. It's simple. It's not on Alfen's side (well, completely at least), it's on `alfen_wallbox` side as well.
> 
> But before I move forward, we need to be clear about one thing: Alfen requires you to use the same TCP connection for sending GET/POST which you used for `api/login` call.
> 
> 1. As I mentioned before, there is an Alfen bug or something that makes it reboot every N hours if you do constant `api/login` requests. Alfen perhaps leaks file descriptors or something.
> 2. However, there is also a problem on `alfen_wallbox` side. In particular, the `self.session` object which does connection pooling which is mandatory has `keepalive_timeout` set to 15s. This is a default value.
> 3. So, when `SCAN_INTERVAL` is any value below 15s (which is true for `SCAN_INTERVAL=5`), `self.session` successfully reuses connections.
> 4. However, when `SCAN_INTERVAL` is, for instance, 30s. `self.session` internally closes TCP connections. As the result, this force it to establish a new connection and hence do a new `api/login` on every sensor update round.
> 
> The solution is simple. We just need to increase `keepalive_interval` to a higher value. I'll prepare a PR for that.

nice information, you can created an MR and i'll merge them to dev for testing

**Comment by WimBra** [comment]
@leeyuentuen , @ikruglov 

pls keep update interval @5sec.
(as discussed here https://github.com/leeyuentuen/alfen_wallbox/discussions/56)

maybe it's an idea to make the interval a variable, to make the user choose between timing

**Comment by leeyuentuen** [comment]
@WimBra  discussion here: https://github.com/leeyuentuen/alfen_wallbox/discussions/114
