### ISSUE TITLE
Alfen charger not charging anymore:  CHARGING_POWER_OFF_LOW_MAXCURRENT

### ISSUE THREAD

**Issue by 2xdehelft** [leeyuentuen/alfen_wallbox#126]
I have a very strange issue that started right about when I started to use this integration. I have no idea this is actually causing this but i'm becoming desperate...

As soon as I connect my car and scan my badge charging should start, but it is then paused because of "External limit 0.0A"
Status of the charger becomes CHARGER_POWER_OFF_LOW_MAXCURRENT.
<img width="632" alt="Alfen charging error" src="https://github.com/leeyuentuen/alfen_wallbox/assets/33652012/7f4d00ea-9276-4125-83d1-be543fb90e75">

But than the strangest thing. I'm using the Stekker APP to externally control the charging so it will only charge when power is cheap. I have been using this for 2 years. They send an external signal (charging profile) to the charger. When I enable the Stekker app and force charging, than the charger does start charging!

I have contacted this company and they explained to me that they don't block charging. There must be something wrong with my default charging profile. But nothing I do changes this strange behaviour. Of Course all settings I can change with the Afen ACE app are set correct and tested...

I even disconnected the charger from the Stekker app and factory resetted the charger. Reset all the settings but still the same problem. (factory reset actually only resets some settings. Logging, transactions, license keys are all retained)

Does anybody know to remove this external limit?

**Comment by leeyuentuen** [comment]
can you check the following values?
 Max. Station Current

i think you have set them on 0A
![image](https://github.com/leeyuentuen/alfen_wallbox/assets/1487966/319f9709-0269-435c-8986-998c424d0592)

**Comment by 2xdehelft** [comment]
<img width="449" alt="image" src="https://github.com/leeyuentuen/alfen_wallbox/assets/33652012/9e3e909d-24fa-41e0-889d-156cf93d285c">
<img width="446" alt="image" src="https://github.com/leeyuentuen/alfen_wallbox/assets/33652012/e03ca6a6-4925-483a-8a9b-48f96f98a068">

How can I get this second one back on 16A? that seems indeed to be the problem. Same setting as in the logging

**Comment by leeyuentuen** [comment]
can you take a look at this beta version and see if you can change the value
https://github.com/leeyuentuen/alfen_wallbox/releases/tag/2.8.5

![image](https://github.com/leeyuentuen/alfen_wallbox/assets/1487966/d8ef7a66-8a9b-424d-bcef-1c7b11cd573b)


for me, i can change it. but not sure in your situation

**Comment by 2xdehelft** [comment]
> can you take a look at this beta version and see if you can change the value https://github.com/leeyuentuen/alfen_wallbox/releases/tag/2.8.5
> 
> ![image](https://private-user-images.githubusercontent.com/1487966/337636064-d8ef7a66-8a9b-424d-bcef-1c7b11cd573b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NTk5ODIsIm5iZiI6MTcxNzc1OTY4MiwicGF0aCI6Ii8xNDg3OTY2LzMzNzYzNjA2NC1kOGVmN2E2Ni04YTliLTQyNGQtYmNlZi0xYzdiMTFjZDU3M2IucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDdUMTEyODAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjAyYjRkZDM3MzE2YWQ1MzBjMGJiOTlhNTU2ODA0OGJjOWIxZjhhZjA2YmUxZGNjODUxYzRmYzBkOTZmZDFhOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.d3gAOJkfpFNOG3c6lC4IBScZ5nK6r_CzwJwWHSY8pJc)
> 
> for me, i can change it. but not sure in your situation

No unfortunately I can change but the setting does not change anything in de charger and changes back to 0 after some time... but that setting does seem to be the problem.. any other ideas?

**Comment by leeyuentuen** [comment]
I'm not sure, but maybe it has been controlled by a load balancer?
which load balancer are you using? modbus or SMR5.0 (see load balancing mode)

maybe you are using too much power at home?

**Comment by leeyuentuen** [comment]
just for compare, this are my values:
![image](https://github.com/leeyuentuen/alfen_wallbox/assets/1487966/67f787ce-bd65-44e0-b60f-050eef1285b0)
![image](https://github.com/leeyuentuen/alfen_wallbox/assets/1487966/25704f72-5734-4d60-8214-e5d8b26ca6f6)

**Comment by 2xdehelft** [comment]
> I'm not sure, but maybe it has been controlled by a load balancer? which load balancer are you using? modbus or SMR5.0 (see load balancing mode)
> 
> maybe you are using too much power at home?

No its in de default charging profile or something like that. I have even disabled loadbalancing completely but charging does not start. It does seem to be the main_external_max_current_socket_1 setting because thats whats in the logging. this setting is just not available in the ACE tool:

<img width="671" alt="image" src="https://github.com/leeyuentuen/alfen_wallbox/assets/33652012/f365d7ac-0df6-46dd-8396-7d9a8da260bc">

**Comment by 2xdehelft** [comment]
![image](https://github.com/leeyuentuen/alfen_wallbox/assets/33652012/986b46e6-49b5-4b29-b483-b21e0a0c9adf)
![image](https://github.com/leeyuentuen/alfen_wallbox/assets/33652012/f055b7c8-72b9-4b8b-ba6c-df6ad456daa8)
![image](https://github.com/leeyuentuen/alfen_wallbox/assets/33652012/5fb2fe5c-039e-4749-ba44-636d93894569)

here are mine...

**Comment by 2xdehelft** [comment]
![Schermafbeelding 2024-06-07 144946](https://github.com/leeyuentuen/alfen_wallbox/assets/33652012/2590c57f-85a1-4983-8eb0-50367e5047a5)
![Schermafbeelding 2024-06-07 144955](https://github.com/leeyuentuen/alfen_wallbox/assets/33652012/9ea49fe9-8290-4a89-8d12-75a13fed267e)
![Schermafbeelding 2024-06-07 145004](https://github.com/leeyuentuen/alfen_wallbox/assets/33652012/ff63fb25-aa78-46b5-83f5-604922be7c29)
![Schermafbeelding 2024-06-07 145020](https://github.com/leeyuentuen/alfen_wallbox/assets/33652012/6f736246-1c0e-4c02-8031-9d5e74db9010)
![Schermafbeelding 2024-06-07 145036](https://github.com/leeyuentuen/alfen_wallbox/assets/33652012/b9c6035b-a102-4e7b-854b-c002da15aba0)
![Schermafbeelding 2024-06-07 145043](https://github.com/leeyuentuen/alfen_wallbox/assets/33652012/09374945-cb93-418a-9a63-8f762176168c)

**Comment by leeyuentuen** [comment]
> <removed image for safety data (tag, id, password,...)>
> 
> Nothing strange right? only the external main...

@2xdehelft i've download the image and will take a look, i've remove them for your own security. because there are some data that is better to not show publicly

**Comment by leeyuentuen** [comment]
i miss an important part of the screenshot:
![image](https://github.com/leeyuentuen/alfen_wallbox/assets/1487966/aaef9e85-c538-4ace-aea2-44f8bc598c87)


can you let me know what the load balancing data source is and the load balancing dsmr smr interface?

**Comment by leeyuentuen** [comment]
> > > <removed image for safety data (tag, id, password,...)>
> > > Nothing strange right? only the external main...
> > 
> > 
> > @2xdehelft i've download the image and will take a look, i've remove them for your own security. because there are some data that is better to not show publicly
> 
> haha oeps :-)
> 
> <img alt="image" width="398" src="https://private-user-images.githubusercontent.com/33652012/337685855-751f6724-5ae1-4d7d-84b0-9e2fd6f31670.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3Njk2OTksIm5iZiI6MTcxNzc2OTM5OSwicGF0aCI6Ii8zMzY1MjAxMi8zMzc2ODU4NTUtNzUxZjY3MjQtNWFlMS00ZDdkLTg0YjAtOWUyZmQ2ZjMxNjcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA3VDE0MDk1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5MTdjM2EzNjMxYmJkZTQwZjZlYjIzZDg5OTJiOTc1MGNjNTYwYzgwMmJjMzVhYTlmNjUwN2YwM2Y3Yzc0YWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oqNl0IYgAMwZv9mZcSo5K_f5ur5-jwRqXDhBPiFSo-o">
> But trust me, with loadbalancing completely off the same problem

i don't see directly incorrect issue, the extra slider that i've add in the beta should change the value, but it seems it goes back in your case..

maybe try to unplug the P1 from your charging pole and change then the  "external max current" and see if that works, then we can be sure that it is not on the load balancing related (you can unplug them on the digital meter side instead of the charging pole

**Comment by 2xdehelft** [comment]
Still no success... Did a factory reset and even imported settings from a friend. Seems there is a "external current limiting" setting that cannot be removed by user. Found one other person online with the same issue but no fix yet.

If you have any more ideas I would love to hear it...

**Comment by 2xdehelft** [comment]
Well after a lot of troubleshooting reported the issue to the chargepoint manager (Vattenfall). They tried to fix it remotely but no success. Last week they sent an engineer tried to fix it onsite but still noting, even after consulting directly with Alfen support the problem could not be fixed, the charging schedule could not be removed.
Yesterday the engineer came back to replace the controlboard and now everything is finally working again 😊

**Comment by leeyuentuen** [comment]
I'll close this, seems it was the issue of a faulty board
