### ISSUE TITLE
HACS install option no longer available?

### ISSUE THREAD

**Issue by rbierings** [leeyuentuen/alfen_wallbox#135]
Can't find the integration anymore in HACS? These install instructions don't seem to work for me:

Installation
Install using HACS (recommended)
If you do not have HACS installed yet visit https://hacs.xyz for installation instructions. In HACS go to the Integrations section hit the big + at the bottom right and search for Alfen Wallbox.

I am able to find the Garo Wallbox integration using this procedure.

**Comment by Roeland54** [comment]
Add this repo as custom repository in hacs: [https://github.com/leeyuentuen/alfen_wallbox](https://github.com/leeyuentuen/alfen_wallbox)

[hacs documentation about adding repositories](https://hacs.xyz/docs/faq/custom_repositories/)

**Comment by rbierings** [comment]
thanks, already got it working!

**Comment by Roeland54** [comment]
Can you close this issue?
