### ISSUE TITLE
number current_limit not working

### ISSUE THREAD

**Issue by Dominic-070** [leeyuentuen/alfen_wallbox#15]
`number.alfen_eve_single_pro_line_current_limit`
Not possible to change te number to `0`
Adjust via service `Alfen Wallbox: set_current_limit` still works. but `number.alfen_eve_single_pro_line_current_limit` is not able to show the number `0`

**Comment by leeyuentuen** [comment]
i think the min value should be then at least 1A

**Comment by leeyuentuen** [comment]
i've create a beta release,
can you take a look if this fix number slider that you want?
https://github.com/leeyuentuen/alfen_wallbox/releases/tag/2.1.11-dev

**Comment by Dominic-070** [comment]
it does display the value 0 now, I just can't set the value 0 in the input number field, I get the error: can't call service number/set_value. connection lost.

**Comment by leeyuentuen** [comment]
take a try on this beta
https://github.com/leeyuentuen/alfen_wallbox/releases/tag/2.1.12-dev

**Comment by Dominic-070** [comment]
![Screenshot_20230708_003536_Home Assistant](https://github.com/leeyuentuen/alfen_wallbox/assets/62623885/19e926cc-8d1b-4027-a2db-780f37972108)
the whole integration has now stopped working. I have a dynamic energy contract. An EV Smart Charging integration calculates how long it takes to charge, finds the cheapest hours and Switches the charger on (16A) and off (0A)

**Comment by leeyuentuen** [comment]
strange, i try it again but didn't seems that the integration crash or stop, can you post me a log file?

**Comment by Dominic-070** [comment]
Everything seems to work fine in version
2.1.15 dev. Also an improvement with the sliders for entering the values.
Thnx again!

**Comment by Dominic-070** [comment]
Everything seems to work fine in version
2.1.15 dev. Also an improvement with the sliders for entering the values.
Thnx again!

**Comment by leeyuentuen** [comment]
> Everything seems to work fine in version 2.1.15 dev. Also an improvement with the sliders for entering the values. Thnx again!

thanks for the confirmation, I change to the slider, otherwise for every value change, it will trigger few calls to alfen wallbox
