### ISSUE TITLE
Values seems not (always) updating, update interval error

### ISSUE THREAD

**Issue by TheBrankman** [leeyuentuen/alfen_wallbox#16]
My values seems not to update regularly.
I have installed the addin just today and got some values, but they seems to stay fixe for longer time.

I also get an error:
"Updating alfen_wallbox select took longer than the scheduled update interval 0:00:30"

If I try to change a setting through Home Assistant, I get also an error (and the values do not change in the Alfen):
"Update for select.alfen_solar_charging_mode fails"
"Update for sensor.alfen_status_code fails"

I have an Alfen Single S-line

**Comment by leeyuentuen** [comment]
are you using the latest version or the dev version?

I know there is an issue connecting to Alfen to change the update if multiple connections exist. like my Eve app opened and running on home assistant, or running various home-assistant instances.

**Comment by TheBrankman** [comment]
> are you using the latest version or the dev version?
> 
> I know there is an issue connecting to Alfen to change the update if multiple connections exist. like my Eve app opened and running on home assistant, or running various home-assistant instances.

Thank you for your quick reply!
I have removed al devices and entities from the Alfen integration. I had tried several different Alfen integrations and maybe they conflicted.

Than I have reinstalled this one. I will see how it goes next days.
You may be right about the errors in the logs may appear because MyEve or ACE installer is also running at the same time...

Actually, running the MyEve app and the ACE installer together gives also several login and stability issues.

**Comment by leeyuentuen** [comment]
> > are you using the latest version or the dev version?
> > I know there is an issue connecting to Alfen to change the update if multiple connections exist. like my Eve app opened and running on home assistant, or running various home-assistant instances.
> 
> Thank you for your quick reply! I have removed al devices and entities from the Alfen integration. I had tried several different Alfen integrations and maybe they conflicted.
> 
> Than I have reinstalled this one. I will see how it goes next days. You may be right about the errors in the logs may appear because MyEve or ACE installer is also running at the same time...
> 
> Actually, running the MyEve app and the ACE installer together gives also several login and stability issues.

the only notice that I got is that the alfen charging pole only (current FW version) 1 or 2 connections simultaneous

**Comment by myhacsint** [comment]
Do you know if the 30 seconds that are hard-coded in alfen.py is a lower limit dictated by the API or could it be set lower?
In addition - wouldn't it make sense to make this value configurable as a setup variable instead of hard-coding it?

**Comment by leeyuentuen** [comment]
> Do you know if the 30 seconds that are hard-coded in alfen.py is a lower limit dictated by the API or could it be set lower? In addition - wouldn't it make sense to make this value configurable as a setup variable instead of hard-coding it?

at the moment it is hardcoded, but it is not easy to store them. or it should be set on the initialization when you add the alfen wallbox, otherwise after the entity has been added, we need to have somewhere to store the changed value.

**Comment by leeyuentuen** [comment]
@TheBrankman I suppose this issue is clear where it came from, so for your part it should be done ok. I'll close this issue to get a clear overview of all the issues on this repo
@myhacsint I'll take a look at it, but I'll close first this issue
