### ISSUE TITLE
Integration not starting api error

### ISSUE THREAD

**Issue by petepall** [leeyuentuen/alfen_wallbox#167]
Hi,

this morning I upgraden to the 2.9.2 version and now the Integration is not starting anymore.
I receive the following:

![IMG_1995](https://github.com/user-attachments/assets/fbbde323-4821-437c-aedd-0e356b971a73)

what can be the cause of this? I did not change anything else.
Tried to reload the integration as well as restart home assistant a couple of times with no luck

**Comment by jvtwout** [comment]
I have als a problem with the API after upgrading to 2.9.2., sensors are unavailable every few seconds.

**Comment by fwestenberg** [comment]
Yes I will do so. @petepall, please inform here if this fix worked for you. Also: is your Alfen up-to-date? 
Please let me know what firmware version you are on.

**Comment by leeyuentuen** [comment]
There is a beta 2 en beta 3

https://github.com/leeyuentuen/alfen_wallbox/releases/tag/2.9.2-beta-2

**Comment by petepall** [comment]
@fwestenberg I’m not able to download these versions.
![IMG_1996](https://github.com/user-attachments/assets/22045100-5655-4bfe-95a7-4ba159b46bb2)

My firmware is 7.0.5-4328 
This is the latest available firmware that is available to me.

**Comment by leeyuentuen** [comment]
> @fwestenberg I’m not able to download these versions. ![IMG_1996](https://private-user-images.githubusercontent.com/42099752/399373302-22045100-5655-4bfe-95a7-4ba159b46bb2.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU1OTQzNDQsIm5iZiI6MTczNTU5NDA0NCwicGF0aCI6Ii80MjA5OTc1Mi8zOTkzNzMzMDItMjIwNDUxMDAtNTY1NS00YmZlLTk1YTctNGJhMTU5YjQ2YmIyLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIzMFQyMTI3MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZmRlODEyMGUwOGUyZTM1NzZkYTIwMDRiOTQ5MmMxNzVjZWIxNjUwOGRhZDU3YmJiODlhN2I1MTEwOWJlMjBiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Tnx3VaP8Pct3EoE7M9JiipqHZUWd41QnhFgkfBVu-8M)
> 
> My firmware is 7.0.5-4328 This is the latest available firmware that is available to me.

Try manual download and replace them in de custom_component folder. I'll later find out why this error is showing up.

**Comment by petepall** [comment]
Installed beta 3 and now it’s working again. No more errors

**Comment by fwestenberg** [comment]
Good to hear it’s working again! @leeyuentuen I can use 2.9.2 as base and add SSL again with config option, right?

**Comment by leeyuentuen** [comment]
> Good to hear it’s working again! @leeyuentuen I can use 2.9.2 as base and add SSL again with config option, right?

I have done it on the beta 2 version
