### ISSUE TITLE
Error when adding integration

### ISSUE THREAD

**Issue by pyrocumulus** [leeyuentuen/alfen_wallbox#19]
I'm trying to add this integration to my HA setup, but it always gives me an error when creating the device. This is the error the log gives me:

```Traceback (most recent call last):
  File "/config/custom_components/alfen_wallbox/config_flow.py", line 55, in _create_device
    await device.init()
  File "/config/custom_components/alfen_wallbox/alfen.py", line 43, in init
    await self.async_update()
  File "/config/custom_components/alfen_wallbox/alfen.py", line 65, in async_update
    await self._do_update()
  File "/config/custom_components/alfen_wallbox/alfen.py", line 121, in _do_update
    self._status = AlfenStatus(response_json_combined, self._status)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alfen_wallbox/alfen.py", line 348, in __init__
    for prop in response["properties"]:
                ~~~~~~~~^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
```

I am using the ACE username + supplied password (QR code information supplied with the charger). The same information I use when connecting through ACE Service Installer. 

Other relevant information:
```
Home Assistant 2023.7.1
Supervisor 2023.07.1
Operating System 10.3 (Home Assistant OS)
Frontend 20230705.1 - latest
```

**Comment by pyrocumulus** [comment]
It was my own fault. The problem was the username. I was using the ACE0XXXXXX ID as the username but I should've just used 'admin'. I was so sure I had already tried that..

So move along, nothing to see here! ;)

**Comment by leeyuentuen** [comment]
nice that you found the issue, i close this ticket
