### ISSUE TITLE
Set curents not available

### ISSUE THREAD

**Issue by LucienHa** [leeyuentuen/alfen_wallbox#21]
In the screen shots on Github, I see "Safe current, Current limit, Max meter current, etc." are visible and adjustable. 
None of these current fields are visible in my integration. 
I added the integration manually and took the latest version (2.2.0). 
Do you have any idea why I can't see these fields. 

Thanks in advance for your response.

**Comment by leeyuentuen** [comment]
did you see something in the logs?

**Comment by LucienHa** [comment]
Thanks for your comment. Is this what you meant?

Logger: homeassistant
Source: components/modbus/modbus.py:398
First occurred: 12:16:51 (8038 occurrences)
Last logged: 13:52:32

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/modbus/sensor.py", line 104, in async_update
    raw_result = await self._hub.async_pymodbus_call(
  File "/usr/src/homeassistant/homeassistant/components/modbus/modbus.py", line 421, in async_pymodbus_call
    result = await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/modbus/modbus.py", line 398, in _pymodbus_call
    result: ModbusResponse = entry.func(address, value, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/pymodbus/client/mixin.py", line 100, in read_holding_registers
    return self.execute(
  File "/usr/local/lib/python3.10/site-packages/pymodbus/client/base.py", line 192, in execute
    return self.transaction.execute(request)
  File "/usr/local/lib/python3.10/site-packages/pymodbus/transaction.py", line 159, in execute
    response, last_exception = self._transact(
  File "/usr/local/lib/python3.10/site-packages/pymodbus/transaction.py", line 273, in _transact
    packet = self.client.framer.buildPacket(packet)
  File "/usr/local/lib/python3.10/site-packages/pymodbus/framer/socket_framer.py", line 218, in buildPacket
    packet = struct.pack(
struct.error: ubyte format requires 0 <= number <= 255

**Comment by LucienHa** [comment]
Here's another one

Logger: pymodbus.logging
Source: components/modbus/modbus.py:398
First occurred: 13:55:37 (1 occurrences)
Last logged: 13:55:37

Connection to (192……………….., 502) failed: [Errno 111] Connection refused

**Comment by leeyuentuen** [comment]
wait. i think you use something else? my integration is not using modbus

**Comment by LucienHa** [comment]
Sorry that's right, in the beginning I approached the charger via Modbus, this was still in the Yaml file. I have now removed this and no longer get an error message on this. But also don't get an error message from your application. What else could I possibly look at?

**Comment by leeyuentuen** [comment]
you can go to the integration and start the debug mode and see if you got error. it could also that your wallbox is limited on the connection, so we can poll information to the wallbox

**Comment by LucienHa** [comment]
I have enabled the Debug. The charger is in-house, I would expect to be able to access it, wouldn't I? The controls present do function.

**Comment by LucienHa** [comment]
![AlfenHa](https://github.com/leeyuentuen/alfen_wallbox/assets/97842608/5a726cb8-a5db-463f-8324-17d0ea748593)

**Comment by leeyuentuen** [comment]
maybe try to re-add the device again to be sure that it is not a issue from before. i don't see the reason why.

maybe adding loggin file here could see more

**Comment by LucienHa** [comment]
I uninstalled it and reinstalled it again. below, the error messages I had in the log. Hopefully this will make it a bit clearer. Just FYI, Back Office is not yet installed with me, that has yet to take place. I don't know if this matters?

Thank you so much for helping to solve this

**Error 1**
Logger: homeassistant.setup
Source: setup.py:347
First occurred: 19:44:40 (1 occurrences)
Last logged: 19:44:40

Unable to prepare setup for platform alfen_wallbox.number: Platform not found (Exception importing custom_components.alfen_wallbox.number).

Deze fout is ontstaan door een aangepaste integratie.

**Error 2**
Logger: homeassistant.loader
Source: custom_components/alfen_wallbox/number.py:36
Integration: Alfen Wallbox (documentation)
First occurred: 19:44:40 (1 occurrences)
Last logged: 19:44:40

Unexpected exception importing platform custom_components.alfen_wallbox.number
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 779, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 796, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/alfen_wallbox/number.py", line 36, in <module>
    AlfenNumberDescription(
TypeError: AlfenNumberDescription.__init__() got an unexpected keyword argument 'mode'

**Comment by leeyuentuen** [comment]
yes this is more clear with the problem. i'll take a look

**Comment by LucienHa** [comment]
Home Assistant 2023.4.5
Supervisor 2023.07.1
Operating System 10.1
Frontend-versie: 20230411.1 - latest

**Comment by leeyuentuen** [comment]
homeassistant 2023.4.5..

maybe let me check why the mode is not existing in that version. normally there is already 2023.7.x version

**Comment by LucienHa** [comment]
I know that there is a newer version available, I already had it installed, but the integration of Enzo did not work properly then. I have therefore restored the backup. If I have to up to date, I will hear it, preferably not.

**Comment by leeyuentuen** [comment]
i'll later try to go back to older ha version to reproduce the issue and see if i can fix them. because i can add mode in the this version, but not sure if that will fix on that old version.

**Comment by LucienHa** [comment]
Thanks again so much for all the effort. If it turns out that it is necessary for me to update, I was planning to do this during my vacation, then I can immediately solve the problems I had with the up date

**Comment by leeyuentuen** [comment]
@LucienHa  can you try the beta version: https://github.com/leeyuentuen/alfen_wallbox/releases/tag/2.2.2-dev
this should fix this issue

**Comment by LucienHa** [comment]
I installed the new HA version, now it works. Only have to solve my problem with the cheapest hours, here he runs into the josn error. Thank you for the assistance

**Comment by LucienHa** [comment]
Sorry, I hadn't seen your comment yet. Do I have to restore a backup.

**Comment by leeyuentuen** [comment]
if the old version worked with your cheapest hours, you could try to rollback.

**Comment by leeyuentuen** [comment]
> Sorry, I hadn't seen your comment yet. Do I have to restore a backup.

we just comment on the same time.

**Comment by LucienHa** [comment]
I'll check tonight if I can get the cheapest hours running, I'll have to go over anyway. Otherwise I go back to the old version. Then I can put it back tonight, it always takes him a few hours to do this.

**Comment by LucienHa** [comment]
Everything works fine with the updated version, just trying to get the prices right. I'm trying to write this out to Json, but it stays empty. If you don't mind, I'd like to see if I can get this resolved, I'll have to go to the new version anyway. If you'd like me to try your modified file, I'd be happy to do so.

**Comment by LucienHa** [comment]
In the new version of HA, I can't get the energy prices right yet. I'm going to restore a backup now and install your modified version of Alfen tonight.

**Comment by LucienHa** [comment]
Old version of Ha is back. The modified version of Alfen loaded and now everything is in the integration.  
Thank you so much for everything.

**Comment by leeyuentuen** [comment]
great, i mark this for next public release
