### ISSUE TITLE
Increase max station current to 32amp

### ISSUE THREAD

**Issue by Dewinn23** [leeyuentuen/alfen_wallbox#22]
Hi,
By default the max amp is set to 16. Is there a way to have the slider go up to 32? Sorry, new to this. 

Thanks!

**Comment by leeyuentuen** [comment]
I don't have the license to test 32A (22KW) parameters, I've create here a beta version can you test them for me if it works?

[Code](https://github.com/leeyuentuen/alfen_wallbox/tree/2.2.1-dev)

**Comment by Dewinn23** [comment]
I'm really new to this but with some assistance I can give it a try...
Thanks for your efforts!

**Comment by leeyuentuen** [comment]
on hacs, you can select the alfen plugin, in the right top you can choose redownload, it will show up a popup, select beta and you will see beta version of that plugin

**Comment by Dewinn23** [comment]
Done, thanks. Seems to work just fine. Just tried to switch the amp from 32 to 23 and the Alfen displays the correct kw. I have a single phase, so 32x230.

**Comment by leeyuentuen** [comment]
released in 2.3.0
