### ISSUE TITLE
Max. Station Current should be taken for upper Limit

### ISSUE THREAD

**Issue by mumpf** [leeyuentuen/alfen_wallbox#35]
Hi,

just a small UI improvement suggestion, resulting from upgrade to 32A:

The setting number.wallbox_max_station_current limits the max. available current the station can deliver. In my case this is set to 16A and is a limit given by the power grid.

The two sliders number.wallbox_current_limit and number.wallbox_alb_safe_current should adjust their upper limit according to number. wallbox_max_station_current. Currentl<, these sliders show both always 32A als max. value and allow accidently a setting of  32A, even in wallbox_max_station_current is 16A.

Is just a detail, but during the last few days I changed the value accidently multiple times to 32A and I simply don't know, how this is handled by the wallbox.

Regards,
Waldemar

**Comment by leeyuentuen** [comment]
I think I can only check if we have a 16A OR 32A depending on the license we bought.

I need to check on it.

**Comment by mumpf** [comment]
My problem is little different. I have a 32A license, by my electricity provider only allows 11 kW, so 16A. That's why the box's wallbox_max_station_current is set to 16A and I am not allowed to increase it. My hope was, that the other controls would get their max values based on wallbox_max_station_current.

But if this is not easy to solve, it's no problem. I'll try to build an other UI sufficient for me.

**Comment by leeyuentuen** [comment]
i can make a dirty fix, to add extra slider with max of 16A, but that's only if i don't find a solution for it

but wait, we have here 2 type of value, one is the max station current, so if you set them on 16A, then you don't need to touch them anymore. we have also a max current, where you can set the value of the current power that you want. Or did i mis something?

**Comment by mumpf** [comment]
> but wait, we have here 2 type of value, one is the max station current, so if you set them on 16A, then you don't need to touch them anymore.

Yes, that's what I ment. Max station current setting is limiting the power. I even do not present the setting in my UI to prevent an accidential change.

> we have also a current_limit, where you can set the value of the current power that you want

Yes, that's one of the parameters I am talking about (the other is wallbox_alb_safe_current). 

>if your station set max on 16A, and you change your current limit to 17A, it will still go to your max station current of 16A

This might be true, I didn't dare to test it. But my main point was, that the UI does not reflect the correct state. My main point was, to set the max value for this parameter dependent on the setting of max_station_current, so you even can't change the value to 17A.

And - to be precise - it is not just about 16A or 32A: A friend of mine is allowed to charge with 20A max. So he would expect the slides max values be 20A. Just as an example.

But if this is not possible or hard to achieve, I will create my own template number to get the right values presented.

Regards, Waldemar

**Comment by leeyuentuen** [comment]
> This might be true, I didn't dare to test it. But my main point was, that the UI does not reflect the correct state. My main point was, to set the max value for this parameter dependent on the setting of max_station_current, so you even can't change the value to 17A.

I haven't tested it yet, but if you want to be sure, you can try to set the max station current to 10 and set the current_limit to 16. And see what the value is. normally it should stay around 10A and never go higher than 16A. if that work then you can be sure that setting on 16A (max station current) and 32A (current_limit) should still stay at 16A

**Comment by leeyuentuen** [comment]
I'll close this ticket, generally, if you set on your station a max of x Amps, your connector should not go over the max amps of the station, even if your connector has higher amps set up

if more discussion need, maybe you can open one on the discussion topic: https://github.com/leeyuentuen/alfen_wallbox/discussions

**Comment by leeyuentuen** [comment]
@mumpf i've reopen a new ticket to solve your initial question,
https://github.com/leeyuentuen/alfen_wallbox/issues/78

there is now a beta version available. It will check if there is a 32A license, if not, it will show only 16A
https://github.com/leeyuentuen/alfen_wallbox/releases/tag/2.7.15
