### ISSUE TITLE
power_connector_max_current

### ISSUE THREAD

**Issue by Dominic-070** [leeyuentuen/alfen_wallbox#49]
in version 2.5.4 when i number.alfen_eve_single_pro_line_power_connector_max_current goes from 0A to 16A it goes after a few seconds back to 0A.

In version 2.5.2 it still works fine.

![Screenshot_20230820_083430_Home Assistant](https://github.com/leeyuentuen/alfen_wallbox/assets/62623885/b87a7b7e-4f17-4727-aa3c-58aee52f782a)

**Comment by leeyuentuen** [comment]
which version do you got this problem?

**Comment by leeyuentuen** [comment]
I've just compare both version:
https://github.com/leeyuentuen/alfen_wallbox/compare/2.5.2...leeyuentuen:alfen_wallbox:2.5.4

I don't see a direct link that this gives this issue.
Could it be that there is another instance running so normally it was 16A but if they can't connect they will return to 0A?

maybe try the latest beta version, it could be that this can fix this issue:
https://github.com/leeyuentuen/alfen_wallbox/releases/tag/2.6.3

**Comment by Dominic-070** [comment]
I think the service is going wrong: Alfen Wallbox: set_current_limit

**Comment by Martin-Yoshi** [comment]
Do you still have the problem in the newest version 2.6.6? I have that version installed and have no issues. 
![IMG_1460](https://github.com/leeyuentuen/alfen_wallbox/assets/81510382/4fa97ea4-33ee-4e1c-b44b-ce59172beb13)

**Comment by leeyuentuen** [comment]
it seems there is some issue with the service set_value, I'll take a look on it later

**Comment by leeyuentuen** [comment]
maybe take a look at this version, could fix that service call issue:
https://github.com/leeyuentuen/alfen_wallbox/releases/tag/2.6.8

**Comment by leeyuentuen** [comment]
@Dominic-070  still got this issue?

**Comment by Dominic-070** [comment]
I'm renovating in our new home and then on vacation. I'll have a look in October but I think it works.
