### ISSUE TITLE
dual socket showing the sensor data

### ISSUE THREAD

**Issue by leeyuentuen** [leeyuentuen/alfen_wallbox#52]

**Comment by WimBra** [comment]
wasn't it possible to rename the sockets 1 entities then making new one's...
(from v2.6.8) V2.6.13 made 14 new entities and I had to disable 14.
Al the previous values gone.... 
(I have a single socket charger)

kind regards

**Comment by leeyuentuen** [comment]
delete the new one but keep the name, rename then the old with that new name. 

it is not the name you need to change but the entity
