### ISSUE TITLE
New internet modem/router: IP address of wallbox changed

### ISSUE THREAD

**Issue by molekuul** [leeyuentuen/alfen_wallbox#53]
How should I handle the issue when the IP address of my Wallbox changed due to a new internet modem/router?

**Comment by leeyuentuen** [comment]
or use set the cp on dhcp and lookup by mac address
or change the new router to the same subnet

**Comment by molekuul** [comment]
I use DHCP offcourse, but when the wallbox gets a new IP address, I can't update the address in homeassistant, I have to remove the wallbox and a a new instance again. Can a update of the configuration be added?

**Comment by leeyuentuen** [comment]
i think the easiest now is remove the cp and readd the cp with new ip.
