### ISSUE TITLE
Version 2.6.2 not markes as "prerelease"

### ISSUE THREAD

**Issue by jeroen94704** [leeyuentuen/alfen_wallbox#54]
I installed this plugin by adding the repository as "custom repo" through HACS. By default, HACS will not show unstable releases. However, 2.6.2 is not marked as "prerelease", even though the release note says it's unstable. This means that right now, by default, version 2.6.2 will get installed, which does indeed not work. Since you don't get to see the release notes in HACS, it's not obvious what's going on and it took me a couple of hours before I realized what was going on. Not a big deal, but I figured I'd report it here since other people run into this.

**Comment by leeyuentuen** [comment]
my bad, i've update them to remove from the production and put them to beta
