### ISSUE TITLE
Configuration: Unexpected error creating device

### ISSUE THREAD

**Issue by gurtjun** [leeyuentuen/alfen_wallbox#63]
Installed the component via HACS (version `2.6.14` because I'm already on HASS `2023.9`).

When configuring the component I get the following error:

```
2023-09-07 07:23:05.734 ERROR (MainThread) [custom_components.alfen_wallbox.config_flow] Unexpected error creating device
Traceback (most recent call last):
File "/config/custom_components/alfen_wallbox/config_flow.py", line 43, in _create_device
await device.init()
^^^^^^^^^^^^^
TypeError: AlfenDevice.init() missing 1 required positional argument: 'hass'
```

Any idea what could be wrong? In case you need more information, feel free to reach out to me 🙂

**Comment by leeyuentuen** [comment]
can you take a look at this beta version: https://github.com/leeyuentuen/alfen_wallbox/releases/tag/2.6.16

**Comment by gurtjun** [comment]
> can you take a look at this beta version: https://github.com/leeyuentuen/alfen_wallbox/releases/tag/2.6.16

seems that I have the same issue as #62 now

**Comment by leeyuentuen** [comment]
can you give me the log?

**Comment by leeyuentuen** [comment]
try this one:
https://github.com/leeyuentuen/alfen_wallbox/releases/tag/2.6.17
