### ISSUE TITLE
Reboot button not working

### ISSUE THREAD

**Issue by Martin-Yoshi** [leeyuentuen/alfen_wallbox#65]
I get an error when I push reboot button. Is this a bug?
![IMG_1557](https://github.com/leeyuentuen/alfen_wallbox/assets/81510382/a6292c0a-7487-45d5-adae-d9e7dd7b8cb5)

**Comment by leeyuentuen** [comment]
yes this is a bug, i'll check on it

**Comment by leeyuentuen** [comment]
take a look at new public release, should fix the button issue, (not test on reboot) but other stuffs like login and logout works

**Comment by Martin-Yoshi** [comment]
I updated and the button works again, but now it seems that the (voltage) sensors are not updating anymore… first that was every +/- 5 or 10 seconds, now it’s already 3 minutes (I also rebooted 3 minutes ago). So t seems it’s (sensors) are not updating anymore.

**Comment by amurray81** [comment]
Came on to report same issue now resolved, but as above have sensor problem. May not be related to this fix

For Max current 1 i can use the slider and the value refreshes fine. If i use an automation to change the value, it does change but the value of the slider does not update. time stamp also remains at time of the most recent integration start

All previous timeout errors seem to have stopped.

**Comment by leeyuentuen** [comment]
my bad, In the meantime i improved a little bit the code, seems broke something,
but try again the latest public release:
https://github.com/leeyuentuen/alfen_wallbox/releases/tag/2.7.5

**Comment by Martin-Yoshi** [comment]
I tested V2.7.5 for 24 hours now, every TV ing seems to work like it should! Also the sensor problem is fixed! If others can conform my findings then we can close this issue.
