### ISSUE TITLE
set_current_limit number.wallbox_power_connector_max_current_socket_1 does not work.

### ISSUE THREAD

**Issue by mumpf** [leeyuentuen/alfen_wallbox#67]
More or less same issue as #31.

The service call to set_current_limit, with the new entity number.wallbox_power_connector_max_current_socket_1 does not work. 

The error is:

> Logger: custom_components.alfen_wallbox.alfen
> Source: custom_components/alfen_wallbox/alfen.py:287
> Integration: Alfen Wallbox ([documentation](https://github.com/leeyuentuen/alfen_wallbox))
> First occurred: 22:04:07 (1 occurrences)
> Last logged: 22:04:07
> 
> Unexpected error on UPDATE VALUE Connection closed
 
Same happens, if I try to use the according slider:
![image](https://github.com/leeyuentuen/alfen_wallbox/assets/14316138/2dca2468-8e0a-44c6-903b-5dfd2e0bfa98)

After a HA reboot I see the value I was sending with the service call. This means, the value is set, but not updated in the UI?

I updated to the newest version 2.7.6 today. 

Regards,
Waldemar

**Comment by leeyuentuen** [comment]
can you take a look at this public release?
https://github.com/leeyuentuen/alfen_wallbox/releases/tag/2.7.7

**Comment by mumpf** [comment]
There is an improvement, thank you.

But it is still not working correctly. 

1. If I use the UI-Element (the slider in the picture above), I see the value change after a while (30 seconds?). This is fine.
2. If I use the service 

> service: alfen_wallbox.set_current_limit
> data:
>   entity_id: number.wallbox_power_connector_max_current_socket_1
>   limit: 8

no UI update happens. I will check later, if the Wallbox receives the new value, I had no chance to go outside to check it.

Ideally, I would need both options, because I am changing the value sometimes (seldom) from UI. More often I change these value by an automation.

There are no messages in the HA-Log.

Regards,
Waldemar

**Comment by leeyuentuen** [comment]
can you take a look at this version?
https://github.com/leeyuentuen/alfen_wallbox/releases/tag/2.7.8
