### ISSUE TITLE
Meter reading only for 1 port

### ISSUE THREAD

**Issue by johnnybegood** [leeyuentuen/alfen_wallbox#69]
Hi,

I have a 2 port Alfen Wallbox (Eve Double Pro-line), the sensor `meter reading` and `Active Power Total` only seem to be taken port 1 into account and not port 2. Most of the other sensors do have a 1 and 2 variant.

**Comment by leeyuentuen** [comment]
thanks for this issue, problem is that I don't have a dual port alfen box. So I need more data to fix them.

do you mind sending me the debugger log? so I can see which API param it should be?
or can you use ace installer and let me know which param_id it should be?
on the single port it s. `2221_22` for meter reading and `2221_16` for Active Power Total

**Comment by johnnybegood** [comment]
Sure,

I don't have the ace installer. The debugger log, is that by enabling debug logging on the integration or something else?

**Comment by leeyuentuen** [comment]
> Sure,
> 
> I don't have the ace installer. The debugger log, is that by enabling debug logging on the integration or something else?

yes turn them on for 2-3 min, and if you stop them, you will get a log. but be sure that during that debugging, both charging port is charging, so I can see some value in it.

**Comment by johnnybegood** [comment]
This is the car charging on port 2, I currently only have 1 car to charge
[home-assistant_alfen_wallbox_2023-09-27T20-11-07.824Z.log](https://github.com/leeyuentuen/alfen_wallbox/files/12742950/home-assistant_alfen_wallbox_2023-09-27T20-11-07.824Z.log)

**Comment by leeyuentuen** [comment]
can you take a look at this beta version if it works?
the socket 1 is also changed name:
- active_power_total to active_power_total_socket_1
- meter_reading to meter_reading_socket_1



https://github.com/leeyuentuen/alfen_wallbox/releases/tag/2.7.10

**Comment by leeyuentuen** [comment]
@johnnybegood can you take a look on the beta version above? to confirm if this solved it?

**Comment by johnnybegood** [comment]
@leeyuentuen looks good

![Screenshot 2023-09-30 at 10 56 50](https://github.com/leeyuentuen/alfen_wallbox/assets/1215440/5f0031ef-8754-48d5-a318-9fe71651ea48)

![Screenshot 2023-09-30 at 10 52 05](https://github.com/leeyuentuen/alfen_wallbox/assets/1215440/2505c95c-689c-49d5-aab0-7d1847bffcc1)

**Comment by leeyuentuen** [comment]
> @leeyuentuen looks good
> 
> ![Screenshot 2023-09-30 at 10 56 50](https://user-images.githubusercontent.com/1215440/271764133-5f0031ef-8754-48d5-a318-9fe71651ea48.png)
> 
> ![Screenshot 2023-09-30 at 10 52 05](https://user-images.githubusercontent.com/1215440/271764137-2505c95c-689c-49d5-aab0-7d1847bffcc1.png)

it will release for public soon
