### ISSUE TITLE
Increase Load Balancing Max Current

### ISSUE THREAD

**Issue by sweebee** [leeyuentuen/alfen_wallbox#84]
You cant set the Load Balancing Max Current higher than 32A in the plugin. I've set mine to 40A in the MyEve app.

I think the max should be set to something like 80A since thats the max for small companies (in The Netherlands atleast). Larger companies can have more but I don't think thats needed.

<img width="535" alt="Scherm­afbeelding 2023-11-27 om 18 40 30" src="https://github.com/leeyuentuen/alfen_wallbox/assets/10496485/d6f8f516-387e-492f-98df-094cdb62af68">

**Comment by leeyuentuen** [comment]
i'll put this in todo list

**Comment by leeyuentuen** [comment]
@sweebee  can you take a look at this beta version?
https://github.com/leeyuentuen/alfen_wallbox/releases/tag/2.7.22
