### ISSUE TITLE
Last fork update?

### ISSUE THREAD

**Issue by pergolafabio** [leeyuentuen/alfen_wallbox#86]
Hi, I see this is a fork, is this version more up to date with new sensors/services? Or will it be merged soon?

Thnx for info, just wanted to know what version I need to install when they are coming to install our Alfen in next weeks

**Comment by leeyuentuen** [comment]
you can always use this fork on hacs, not sure when it will be merge with the parent branch

**Comment by pergolafabio** [comment]
Do you have a PR ready for it?

**Comment by leeyuentuen** [comment]
not yet

**Comment by leeyuentuen** [comment]
@pergolafabio use in hacs this repository: https://github.com/leeyuentuen/alfen_wallbox

**Comment by pergolafabio** [comment]
still waiting for my Alfen delivery :-)
