### ISSUE TITLE
Not possible to connect with alfen tool after itegration 

### ISSUE THREAD

**Issue by SpeedlimitsB** [leeyuentuen/alfen_wallbox#89]
Hi there and thanks for your effort . 

Could it be that ones you done the integration in AH . you cant loging with the alfen tool ?

**Comment by Martin-Yoshi** [comment]
Hey SpeedlimitsB,

This is not a bug/ issue. The integration keeps a constant connection open with the charger. So if you want to use the Alfen tool, you have to (temporarily) deactivate the integration.  Everything comes with a price haha. 

So yes, this behavior is normal. 😊

greets,

Martin

**Comment by SpeedlimitsB** [comment]
Thanks !!
