### ISSUE TITLE
Feature request - Add service / option to change solar charging mode

### ISSUE THREAD

**Issue by Emacee** [leeyuentuen/alfen_wallbox#9]
Would be nice to integrate a service or input_select for the different charging modes;

- Disabled
- Green
- Comfort

Is it possbile to create a service for this feature? 
I tried to add a service but it's not working for me, I'll add it to this repo as soon as I have the time.

**Comment by leeyuentuen** [comment]
i think it will be available on the new dev branch: (see readme screenshot)
https://github.com/leeyuentuen/alfen_wallbox/tree/dev

**Comment by leeyuentuen** [comment]
Fix on new release https://github.com/leeyuentuen/alfen_wallbox/releases/tag/2.1.7
