### ISSUE TITLE
Who has authorized?

### ISSUE THREAD

**Issue by banybeer** [leeyuentuen/alfen_wallbox#94]
We are having 2 RFID cards for authorization. For each one a different backend reimbursement process is triggered.
Does anyone know if there is already a sensor showing me which RFID card has authorized? Didn’t find any yet.

**Comment by leeyuentuen** [comment]
did you see them on my eve app with card goes to which backend?

**Comment by TeddyTBP** [comment]
I would be very interested in a sensor with the active RFID badge during charging. We could then link ID to a name and inform people if its time to get their car moved

**Comment by leeyuentuen** [comment]
testing in beta version: 
https://github.com/leeyuentuen/alfen_wallbox/releases/tag/2.7.33

![image](https://github.com/leeyuentuen/alfen_wallbox/assets/1487966/033cee83-4919-4b82-afb8-a02aecac5667)

**Comment by leeyuentuen** [comment]
i need someone with multiple tags to let me know of this works

**Comment by TeddyTBP** [comment]
Just installed .33 and i can see last tag is populated in the two fields. Wil do some more testing. 

Not sure if its possible: but could we have one sensor where standard value is non and then on start we see new value en and stop we go back to none? 

Kn this matter you would have a status of the card during transaction but if done and transaction is closed we would see none.  

If then in HA we goto show more we would see who has charged and for how long.

**Comment by leeyuentuen** [comment]
I try to add the charging time and the total charge amount. but I think the transaction will not instantly update, maybe every 15 minutes or something like that. But maybe good try for the beginning

![Screenshot 2024-04-19 at 10 37 59](https://github.com/leeyuentuen/alfen_wallbox/assets/1487966/c9e68a4c-2524-4605-9431-20fb17553364)

**Comment by leeyuentuen** [comment]
@TeddyTBP i think you see now the thing you needed?

@banybeer i think you can see the tag that is using the wallbox?

**Comment by TeddyTBP** [comment]
Hi, I can confirm that the vallues added in .36 are populating for me after the charge session has stopped during the session i didn't notice change. 

<img width="556" alt="image" src="https://github.com/leeyuentuen/alfen_wallbox/assets/134924704/2ce9d3df-f258-4387-8396-577d3f4d6276">

**Comment by TeddyTBP** [comment]
For the Start en stop session it seems double the values do change if i scan another tag but if twice the same tag is used then there is no change in value. 

In this case i think what would work beter is 1 sensor where that state is none by default. on start it gets the ID of the tag en on stop it reverts back to none. in this case you get a bar graph in the history with all the sessions marked inline. In the end it could like like the altered screenshot below. 
![image](https://github.com/leeyuentuen/alfen_wallbox/assets/134924704/078c5af5-fa83-4237-a81a-0b6fe22b442f)

**Comment by leeyuentuen** [comment]
> Hi, I can confirm that the vallues added in .36 are populating for me after the charge session has stopped during the session i didn't notice change.
> 
> <img alt="image" width="556" src="https://private-user-images.githubusercontent.com/134924704/324269175-2ce9d3df-f258-4387-8396-577d3f4d6276.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3MjUwNDcsIm5iZiI6MTcxMzcyNDc0NywicGF0aCI6Ii8xMzQ5MjQ3MDQvMzI0MjY5MTc1LTJjZTlkM2RmLWYyNTgtNDM4Ny04Mzk2LTU3N2QzZjRkNjI3Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMVQxODM5MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNmYyODk2N2FiYWUwNTY5NjBhMDI0Zjg0Y2Y4ODczN2Y1ZDlkYjQ2MjFhOWI4M2QwODNmNTc4Yjg5ZmM3NzJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.iQ1EcV0Z7qaubKgnhKbz-jJfErB7IXMWKJrxIJ0jDJ8">

yes i notice this, there will be update soon (maybe within 1h)

**Comment by leeyuentuen** [comment]
> For the Start en stop session it seems double the values do change if i scan another tag but if twice the same tag is used then there is no change in value.
> 
> In this case i think what would work beter is 1 sensor where that state is none by default. on start it gets the ID of the tag en on stop it reverts back to none. in this case you get a bar graph in the history with all the sessions marked inline. In the end it could like like the altered screenshot below. ![image](https://private-user-images.githubusercontent.com/134924704/324269503-078c5af5-fa83-4237-a81a-0b6fe22b442f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3MjUwNDcsIm5iZiI6MTcxMzcyNDc0NywicGF0aCI6Ii8xMzQ5MjQ3MDQvMzI0MjY5NTAzLTA3OGM1YWY1LWZhODMtNDIzNy1hODFhLTBiNmZlMjJiNDQyZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMVQxODM5MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNDg5NzRkYmJjZGQxMzgyNWU4ZTc3MmM5MWMwMzIxZjMzMjc1OTA4ZTEyODg1OGQ5NGE1NmZjNWFmOTY2MDFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZEl5Gua1p7TiaF4Lr3CrPLw7d9thRZncQ4Ia01Z6pFQ)

i'll maybe remove the start and stop tag, only put the tag

**Comment by leeyuentuen** [comment]
@TeddyTBP latest beta has been updated, can you take a look if it is what we need?

**Comment by VmaxTurbo** [comment]
Would it be possible to start a charging session from HA, using my tag ID, without having to scan it at the RFID reader on the wallbox every time? Automating charging sessions from HA at low costs would be a nice to have...

**Comment by leeyuentuen** [comment]
> Would it be possible to start a charging session from HA, using my tag ID, without having to scan it at the RFID reader on the wallbox every time? Automating charging sessions from HA at low costs would be a nice to have...

not checked yet. but i'm just tag them but set the amp to 0. if i want to charge, i set them max to 6 - 16A

**Comment by aritmeester** [comment]
> For the Start en stop session it seems double the values do change if i scan another tag but if twice the same tag is used then there is no change in value.
> 
> In this case i think what would work beter is 1 sensor where that state is none by default. on start it gets the ID of the tag en on stop it reverts back to none. in this case you get a bar graph in the history with all the sessions marked inline. In the end it could like like the altered screenshot below. 

If I were you, I wouldn't post my Tag ID online. This way your tag can easily be misused.

**Comment by leeyuentuen** [comment]
> > For the Start en stop session it seems double the values do change if i scan another tag but if twice the same tag is used then there is no change in value.
> > In this case i think what would work beter is 1 sensor where that state is none by default. on start it gets the ID of the tag en on stop it reverts back to none. in this case you get a bar graph in the history with all the sessions marked inline. In the end it could like like the altered screenshot below.
> 
> If I were you, I wouldn't post my Tag ID online. This way your tag can easily be misused.

i've just changed that post. thanks for that

**Comment by banybeer** [comment]
thanks @leeyuentuen ! Just saw that it was added with the "Tag" and nicely works. Tried it with different RFID cards - perfect! will add it now in automations. If i come across an issues i will let you know.

**Comment by citoki** [comment]
> You see in the transaction the card tags. The tags are the important information. Best case would be even to have sensors which sum up the consumption in kWh per recognized tag.

@banybeer for that I added a utility meter with two tariffs. To count on the respective tariff, I added two automations (could also be done in one automation), to count the `kWh`of the active tag: https://github.com/leeyuentuen/alfen_wallbox/discussions/88#discussioncomment-11195982

**Comment by BIERAAP** [comment]
anyone a clue when this will be pushed to the master release?
