### ISSUE TITLE
HACS integration not found.

### ISSUE THREAD

**Issue by GrazzV1** [leeyuentuen/alfen_wallbox#98]
HACS integration not found.
![image](https://github.com/leeyuentuen/alfen_wallbox/assets/10562221/9995036b-898a-4cb3-8bf6-23147c94cb89)

Core: 2024.2.2
Supervisor: 2024.01.1
Operating System: 11.5
Frontend: 20240207.1
HACS: 1.34.0

**Comment by leeyuentuen** [comment]
did you first add the custom repo in hacs?

**Comment by GrazzV1** [comment]
@leeyuentuen, that's what I'm trying to do in the screenshot.

**Comment by leeyuentuen** [comment]
in hacs choose the 3 dots (...) not on the + button

![Screenshot_2024-02-20-22-54-31-53_c3a231c25ed346e59462e84656a70e50~2](https://github.com/leeyuentuen/alfen_wallbox/assets/1487966/8f600a29-bed2-48e0-8c3e-e641386eeec4)


![Screenshot_2024-02-20-22-54-40-81_c3a231c25ed346e59462e84656a70e50](https://github.com/leeyuentuen/alfen_wallbox/assets/1487966/1295a94e-b8fc-4cc5-8829-965b34355a96)

**Comment by GrazzV1** [comment]
@leeyuentuen, I'm stupid and I'm sorry I wasted your time. I forgot about this step. Thank you for your help.
